steps:
  # stage1 install the app dependencies
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app']
  # stage2 install the app dependencies
  - name: 'gcr.io/cloud-builders/deploy'
    args: [ 'deploy' ]
  # stage3 install the app dependencies
  - name: 'gcr.io/cloud-builders/deploy'
    args: [ 'app.dev.yaml' ]
#steps:
#- name: "gcr.io/cloud-builders/gcloud"
#  args: ["app", "deploy", "app.dev.yaml"]
#timeout: "1600s"